version: '3.8'
services:
  next-app:
    build: ./next-app
    ports:
      - "3000:3000"
    volumes:
      - ./next-app:/app
      # 必要に応じて Docker ソケットをマウント（セキュリティには注意）
      - /var/run/docker.sock:/var/run/docker.sock
  executor:
    build: ./executor
    image: executor
